spring.application.name=ksan
server.servlet.session.persistent=false
spring.datasource.url=jdbc:postgresql://localhost:5432/agridb
spring.datasource.username=postgres
spring.datasource.password=manager
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.security.jwt.exp.time=86400000
spring.security.jwt.secret.key=ubgYnLUpgUxM8XiGOqj52NojEINsXgNpofpmd1yl/tHq6QjChPlOEWwtNrwPE2nr8Axu8Vv1YZ85pSycVeBNqR22es0HBQFgri4EczhRG1Y=